[tool.poetry]
name = "data-pipeline"
version = "0.1.0"
description = ""
authors = ["André <andrejunior573@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.10.12"
requests = "^2.32.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
